% Solve an Input-Output Fitting problem with a Neural Network
% Script generated by Neural Fitting app
% Created Tue Feb 02 14:23:59 CET 2016
%
close all;
clear all;

trialnumber = 1;
offset = 1;
for trialnumber = 1:1
 if trialnumber == 1
    filename1 = 'FeaturesTrial7.xlsx';
    filename2 = 'FeaturesTrial8.xlsx';
    filename3 = 'FeaturesTrial9.xlsx';
    filename4 = 'FeaturesTrial10.xlsx';
    filename7 = 'FeaturesTrial7.mat';
    filename8 = 'FeaturesTrial8.mat';
    filename9 = 'FeaturesTrial9.mat';
    filename10 = 'FeaturesTrial10.mat';

elseif trialnumber == 2
    filename1 = 'FeaturesTrial1.xlsx';
    filename2 = 'FeaturesTrial2.xlsx';
    filename3 = 'FeaturesTrial5.xlsx';
    filename4 = 'FeaturesTrial6.xlsx';
    filename5 = 'FeaturesTrial9.xlsx';
    filename6 = 'FeaturesTrial10.xlsx';
elseif trialnumber == 3
    filename1 = 'FeaturesTrial5.xlsx';
    filename2 = 'FeaturesTrial6.xlsx';
    filename3 = 'FeaturesTrial9.xlsx';
    filename4 = 'FeaturesTrial10.xlsx';
    filename5 = 'FeaturesTrial7.xlsx';
    filename6 = 'FeaturesTrial8.xlsx';
elseif trialnumber == 4
    filename1 = 'FeaturesTrial1.xlsx';
    filename2 = 'FeaturesTrial2.xlsx';
    filename3 = 'FeaturesTrial10.xlsx';
    filename4 = 'FeaturesTrial7.xlsx';
    filename5 = 'FeaturesTrial8.xlsx';
    filename6 = 'FeaturesTrial9.xlsx';
end

data = importdata(filename1);
target = data.data(101:4100,1)';
RMS = data.data(101:4100,3)';
lgVariance = data.data(101:4100,4)';
Variance = data.data(101:4100,5)';
sEMG_t = data.data((101:4100),8)';
RMS_t = data.data((101:4100),9)';
lgVariance_t = data.data((101:4100),10)';
Variance_t = data.data((101:4100),11)';
save(filename7, 'data');

data2 = importdata(filename2);
target2 = data2.data(101:4100,1)';
RMS2 = data2.data(101:4100,3)';
lgVariance2 = data2.data(101:4100,4)';
Variance2 = data2.data(101:4100,5)';
sEMG_t2 = data2.data((101:4100),8)';
RMS_t2 = data2.data((101:4100),9)';
lgVariance_t2 = data2.data((101:4100),10)';
Variance_t2 = data2.data((101:4100),11)';
save(filename8, 'data2');

data3 = importdata(filename3);
target3 = data3.data(101:4100,1)';
RMS3 = data3.data(101:4100,3)';
lgVariance3 = data3.data(101:4100,4)';
Variance3 = data3.data(101:4100,5)';
sEMG_t3 = data3.data((101:4100),8)';
RMS_t3 = data3.data((101:4100),9)';
lgVariance_t3 = data3.data((101:4100),10)';
Variance_t3 = data3.data((101:4100),11)';
save(filename9, 'data3');

data4 = importdata(filename4);
target4 = data4.data(101:4100,1)';
RMS4 = data4.data(101:4100,3)';
lgVariance4 = data4.data(101:4100,4)';
Variance4 = data4.data(101:4100,5)';
sEMG_t4 = data4.data((101:4100),8)';
RMS_t4 = data4.data((101:4100),9)';
lgVariance_t4 = data4.data((101:4100),10)';
Variance_t4 = data4.data((101:4100),11)';
save(filename10, 'data4');

end;


